#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
AgriSahayak - Smart Agriculture Platform
Startup script: manages services, validates environment, launches the server.

Usage:
  python start.py              # Normal start (auto-rebuilds React if needed)
  python start.py --clean      # Wipe node_modules + fresh npm install
  python start.py --port 8080  # Use a custom port
  python start.py --prod       # Production mode (no --reload, faster startup)
  python start.py --no-browser # Skip auto-opening the browser
  python start.py --check      # Run all service checks then exit (no server)
  python start.py --help       # Show this help
"""

import subprocess
import sys
import os
import time
import webbrowser
import socket
import shutil
import json
import threading
import argparse
from urllib import request

# Ensure UTF-8 output on Windows (needed for emoji in terminals)
try:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    if hasattr(sys.stderr, "reconfigure"):
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

try:
    import requests as _requests
except ImportError:
    _requests = None

# ─────────────────────────────────────────────────────────
# Default configuration (overridden by CLI args)
# ─────────────────────────────────────────────────────────
DEFAULT_PORT      = 8000
HOST              = "0.0.0.0"
OLLAMA_PORT       = 11434
OLLAMA_URL        = f"http://localhost:{OLLAMA_PORT}"

# ─────────────────────────────────────────────────────────
# ANSI colours (auto-disabled on Windows without ANSI support)
# ─────────────────────────────────────────────────────────
def _ansi_support() -> bool:
    if sys.platform == "win32":
        # Windows 10 v1511+ supports ANSI in ConHost; check ANSICON / WT
        return (
            os.environ.get("WT_SESSION")         # Windows Terminal
            or os.environ.get("ANSICON")
            or os.environ.get("TERM_PROGRAM") == "vscode"
            or "PYCHARM" in os.environ.get("PYCHARM_HOSTED", "")
        )
    return True

_USE_COLOR = _ansi_support()

def _c(code: str, text: str) -> str:
    return f"\033[{code}m{text}\033[0m" if _USE_COLOR else text

def ok(msg):   print(_c("32", "  [OK]  ") + msg)
def warn(msg): print(_c("33", " [WARN] ") + msg)
def err(msg):  print(_c("31", " [FAIL] ") + msg)
def info(msg): print(_c("36", " [INFO] ") + msg)
def head(msg): print(_c("1;37", msg))


# ─────────────────────────────────────────────────────────
# .env helpers
# ─────────────────────────────────────────────────────────
def parse_env_file(env_path: str) -> dict:
    """Parse a .env file into a dict (values only; does not modify os.environ)."""
    values = {}
    if not os.path.exists(env_path):
        return values
    try:
        with open(env_path, "r", encoding="utf-8") as f:
            for raw_line in f:
                line = raw_line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, value = line.split("=", 1)
                key   = key.strip()
                value = value.strip().strip('"').strip("'")
                if key:
                    values[key] = value
    except Exception as e:
        warn(f"Could not parse {env_path}: {e}")
    return values


def prepare_runtime_env(project_root: str, backend_dir: str) -> dict:
    """
    Build the runtime environment for the FastAPI process:
      1. OS environment
      2. backend/.env  (lowest priority)
      3. project .env  (highest priority for local dev)
    Returns the merged dict; prints any key-conflict warnings.
    """
    runtime_env    = os.environ.copy()
    backend_env    = parse_env_file(os.path.join(backend_dir,    ".env"))
    root_env       = parse_env_file(os.path.join(project_root,   ".env"))

    # Merge in priority order (root_env wins)
    runtime_env.update(backend_env)
    runtime_env.update(root_env)

    # JWT_SECRET_KEY normalisation
    b_jwt = backend_env.get("JWT_SECRET_KEY")
    r_jwt = root_env.get("JWT_SECRET_KEY")
    if b_jwt and r_jwt and b_jwt != r_jwt:
        warn("JWT_SECRET_KEY differs between backend/.env and .env — using .env value.")

    if not runtime_env.get("JWT_SECRET_KEY") and runtime_env.get("SECRET_KEY"):
        runtime_env["JWT_SECRET_KEY"] = runtime_env["SECRET_KEY"]
        info("JWT_SECRET_KEY not set; using SECRET_KEY for this run.")

    return runtime_env


def generate_env_template(project_root: str):
    """Generate a starter .env if none exists."""
    env_path = os.path.join(project_root, ".env")
    if os.path.exists(env_path):
        return
    import secrets
    template = f"""# AgriSahayak Environment – generated by start.py
# Fill in the values below and restart.

SECRET_KEY={secrets.token_hex(32)}
JWT_SECRET_KEY={secrets.token_hex(32)}

# Gemini 2.5 Flash (weather intelligence + crop advisory + market advisory)
GEMINI_API_KEY=

# Market Prices – AGMARKNET / data.gov.in (optional, enhances market page)
MARKET_API_KEY=

# Supabase (optional – fallback is local SQLite)
SUPABASE_URL=
SUPABASE_KEY=

# Ollama (local LLM server for chatbot + weather summaries)
OLLAMA_URL=http://localhost:11434
OLLAMA_MODEL=llama3.2:latest

# Sentinel-2 (Copernicus Data Space Ecosystem)
SENTINEL_CLIENT_ID=
SENTINEL_CLIENT_SECRET=

# Twilio WhatsApp Bot ("Zero-G fallback")
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_WHATSAPP_NUMBER=+14155238886
"""
    try:
        with open(env_path, "w", encoding="utf-8") as f:
            f.write(template)
        info(f".env not found – created template at {env_path}")
        info("Fill in GEMINI_API_KEY (required for AI features) then restart.")
    except Exception as e:
        warn(f"Could not create .env template: {e}")


# ─────────────────────────────────────────────────────────
# Network helpers
# ─────────────────────────────────────────────────────────
def http_get_json(url: str, timeout: float):
    if _requests is not None:
        r = _requests.get(url, timeout=timeout)
        return r.status_code, r.json()
    with request.urlopen(url, timeout=timeout) as r:
        return r.getcode(), json.loads(r.read().decode())


def is_port_in_use(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        return s.connect_ex(("localhost", port)) == 0


def get_lan_ip() -> str:
    """Return the machine's LAN IP address (best-effort)."""
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
            s.connect(("8.8.8.8", 80))
            return s.getsockname()[0]
    except Exception:
        return "127.0.0.1"


def kill_existing_server(port: int):
    """Kill any process occupying *port* (best-effort)."""
    if sys.platform == "win32":
        try:
            result = subprocess.run(
                ["netstat", "-ano"], capture_output=True, text=True, timeout=10
            )
            for line in result.stdout.splitlines():
                if f":{port}" in line and "LISTENING" in line:
                    pid = line.split()[-1]
                    if pid.isdigit():
                        subprocess.run(
                            ["taskkill", "/F", "/PID", pid],
                            capture_output=True, timeout=5
                        )
        except Exception:
            pass
    else:
        os.system(f"lsof -ti :{port} | xargs kill -9 2>/dev/null")


# ─────────────────────────────────────────────────────────
# Ollama helpers
# ─────────────────────────────────────────────────────────
def is_ollama_running() -> bool:
    try:
        code, _ = http_get_json(f"{OLLAMA_URL}/api/tags", timeout=3)
        return code == 200
    except Exception:
        return False


def get_ollama_models() -> list:
    try:
        code, data = http_get_json(f"{OLLAMA_URL}/api/tags", timeout=5)
        if code == 200:
            return [m.get("name", "") for m in data.get("models", [])]
    except Exception:
        pass
    return []


def start_ollama() -> bool:
    """Start Ollama server with GPU acceleration if not already running."""
    if is_ollama_running():
        ok("Ollama already running")
        return True

    print("  Starting Ollama with GPU acceleration...")

    ollama_exe = None
    if sys.platform == "win32":
        candidates = [
            os.path.expandvars(r"%LOCALAPPDATA%\Programs\Ollama\ollama.exe"),
            os.path.expandvars(r"%PROGRAMFILES%\Ollama\ollama.exe"),
            shutil.which("ollama"),
        ]
        ollama_exe = next((p for p in candidates if p and os.path.exists(p)), None)
    else:
        ollama_exe = shutil.which("ollama")

    if not ollama_exe:
        err("Ollama not found – install from https://ollama.ai")
        warn("Chatbot and local AI summaries will be unavailable.")
        return False

    gpu_env = os.environ.copy()
    gpu_env.update({
        "OLLAMA_NUM_GPU":        "999",   # Offload all layers to GPU
        "OLLAMA_FLASH_ATTENTION": "1",    # Flash-attention for faster inference
        "OLLAMA_MAX_LOADED_MODELS": "1",  # Keep one model warm
        "OLLAMA_KEEP_ALIVE":     "15m",   # Keep model in VRAM 15 min between calls
    })

    popen_kwargs = dict(
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        env=gpu_env,
    )
    if sys.platform == "win32":
        popen_kwargs["creationflags"] = subprocess.CREATE_NO_WINDOW

    try:
        subprocess.Popen([ollama_exe, "serve"], **popen_kwargs)
        for i in range(12):
            time.sleep(1)
            if is_ollama_running():
                ok("Ollama started successfully")
                return True
            print(f"  Waiting for Ollama... ({i+1}/12)", end="\r")
        warn("Ollama may not have started – check 'ollama serve' manually")
        return False
    except Exception as e:
        err(f"Failed to start Ollama: {e}")
        return False


def warmup_ollama_background():
    """After the server starts, pre-load the Ollama model into GPU VRAM."""
    time.sleep(6)  # Wait for FastAPI to finish initialising
    try:
        models = get_ollama_models()
        if not models:
            return
        # Pick a lightweight model that is actually downloaded
        preferred = ["qwen2.5:1.5b", "phi3:mini", "gemma2:2b", "llama3.2:latest"]
        model = next((m for m in preferred if m in models), models[0])
        url = f"{OLLAMA_URL}/api/generate"
        payload = json.dumps({
            "model": model,
            "prompt": "Hi",
            "stream": False,
            "options": {"num_predict": 1, "num_gpu": 999},
        }).encode()
        req = request.Request(url, data=payload, method="POST",
                              headers={"Content-Type": "application/json"})
        with request.urlopen(req, timeout=30):
            pass
        info(f"Ollama model '{model}' warmed up in GPU VRAM")
    except Exception:
        pass  # Silence – warmup is best-effort


# ─────────────────────────────────────────────────────────
# GPU detection
# ─────────────────────────────────────────────────────────
def check_gpu() -> str:
    """Return a short GPU description, or empty string if CUDA not available."""
    try:
        import torch
        if torch.cuda.is_available():
            name  = torch.cuda.get_device_name(0)
            total = torch.cuda.get_device_properties(0).total_memory // (1024 ** 2)
            return f"{name} ({total} MB VRAM)"
    except Exception:
        pass
    return ""


# ─────────────────────────────────────────────────────────
# React frontend builder
# ─────────────────────────────────────────────────────────
def build_react_frontend(project_root: str, force_clean: bool = False):
    """Build the React frontend if it is missing or outdated."""
    frontend_src  = os.path.join(project_root, "frontend-src")
    frontend_dist = os.path.join(project_root, "frontend-dist")
    dist_index    = os.path.join(frontend_dist, "index.html")
    package_json  = os.path.join(frontend_src,  "package.json")
    package_lock  = os.path.join(frontend_src,  "package-lock.json")
    node_modules  = os.path.join(frontend_src,  "node_modules")

    if not os.path.isdir(frontend_src):
        warn("frontend-src/ not found – skipping React build")
        return

    npm_exe = shutil.which("npm")
    if not npm_exe:
        warn("npm not in PATH – skipping React build")
        info("Install Node.js 18+ from https://nodejs.org")
        return

    # --clean: wipe node_modules
    if force_clean and os.path.isdir(node_modules):
        print("  Removing node_modules for clean reinstall...")
        try:
            if sys.platform == "win32":
                subprocess.run(
                    ["cmd", "/c", "rmdir", "/s", "/q", node_modules],
                    capture_output=True, timeout=120
                )
            else:
                shutil.rmtree(node_modules)
            print("  node_modules removed")
        except Exception as e:
            warn(f"Could not remove node_modules: {e}")

    # Decide if npm install is needed
    lock_stamp = os.path.join(node_modules, ".package-lock.json")
    stamp      = lock_stamp if os.path.exists(lock_stamp) else node_modules
    needs_install = not os.path.isdir(node_modules) or force_clean
    if not needs_install and os.path.exists(stamp):
        stamp_mtime = os.path.getmtime(stamp)
        for watched in (package_json, package_lock):
            if os.path.exists(watched) and os.path.getmtime(watched) > stamp_mtime:
                needs_install = True
                break

    if needs_install:
        label = "Clean installing" if force_clean else "Installing"
        print(f"  {label} npm dependencies...")
        result = subprocess.run(
            [npm_exe, "install"], cwd=frontend_src, capture_output=True, text=True
        )
        if result.returncode != 0:
            err(f"npm install failed:\n{result.stderr[-800:]}")
            return
        ok("npm install complete")

    # Decide if build is needed
    dist_mtime   = os.path.getmtime(dist_index) if os.path.exists(dist_index) else 0
    needs_build  = not os.path.exists(dist_index)

    if not needs_build:
        config_files = [
            package_json, package_lock,
            os.path.join(frontend_src, "index.html"),
            os.path.join(frontend_src, "vite.config.js"),
            os.path.join(frontend_src, "tailwind.config.js"),
            os.path.join(frontend_src, "postcss.config.js"),
        ]
        for f in config_files:
            if os.path.exists(f) and os.path.getmtime(f) > dist_mtime:
                needs_build = True
                break

    if not needs_build:
        src_dir = os.path.join(frontend_src, "src")
        for root_dir, _, files in os.walk(src_dir):
            for fname in files:
                if os.path.getmtime(os.path.join(root_dir, fname)) > dist_mtime:
                    needs_build = True
                    break
            if needs_build:
                break

    if not needs_build:
        ok("React build is up to date")
        return

    print("  Building React app (Vite 5)...")
    result = subprocess.run(
        [npm_exe, "run", "build"], cwd=frontend_src, capture_output=True, text=True
    )
    if result.returncode == 0:
        ok("React build complete  →  frontend-dist/")
        sw = os.path.join(project_root, "frontend-dist", "sw.js")
        if os.path.exists(sw):
            info("sw.js present – PWA offline mode enabled")
        else:
            warn("sw.js missing – ensure frontend-src/public/sw.js exists")
    else:
        err(f"React build failed:\n{result.stderr[-1200:]}")


# ─────────────────────────────────────────────────────────
# ML model checks
# ─────────────────────────────────────────────────────────
def check_ml_models(project_root: str):
    """Report which trained ML model files are present."""
    ml_dir = os.path.join(project_root, "ml", "models")
    models = {
        "Crop Recommender (Neural Net)": "crop_recommender_nn.pth",
        "Crop Recommender (RF backup)":  "crop_recommender_rf.pkl",
        "Yield Predictor":               "yield_predictor.joblib",
        "Pest Classifier (dir)":         "pest_classifier",
    }
    all_present = True
    for label, filename in models.items():
        path = os.path.join(ml_dir, filename)
        exists = os.path.exists(path)
        if exists:
            ok(f"{label}")
        else:
            warn(f"{label} not found ({filename})")
            all_present = False
    if not all_present:
        info("Missing models use rule-based fallbacks – run ml/training/* to train.")
    return all_present


# ─────────────────────────────────────────────────────────
# Frontend npm package validator
# ─────────────────────────────────────────────────────────
def check_npm_packages(project_root: str) -> bool:
    """Verify that critical npm packages are declared in frontend-src/package.json."""
    pkg_json_path = os.path.join(project_root, "frontend-src", "package.json")
    if not os.path.exists(pkg_json_path):
        warn("frontend-src/package.json not found – skipping package check")
        return True
    try:
        with open(pkg_json_path, "r", encoding="utf-8") as f:
            pkg = json.load(f)
    except Exception as e:
        warn(f"Could not parse package.json: {e}")
        return True

    all_deps = {**pkg.get("dependencies", {}), **pkg.get("devDependencies", {})}

    # Packages added during feature development that must be present
    required = {
        "three":           "3D Globe visualisation  (Home page hero)",
        "canvas-confetti": "CropCycle timeline confetti animation",
        "html2canvas":     "Analytics export  –  screenshot to PDF/PNG",
        "jspdf":           "Analytics export  –  PDF generation",
    }

    missing = []
    for name, desc in required.items():
        if name in all_deps:
            ok(f"{name}  -  {desc}")
        else:
            warn(f"{name} not found in package.json  -  {desc}")
            missing.append(name)

    if missing:
        info("Fix: cd frontend-src && npm install " + " ".join(missing))
    return len(missing) == 0


# ─────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────
def parse_args():
    p = argparse.ArgumentParser(
        description="AgriSahayak startup script",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument("--clean",      action="store_true", help="Wipe node_modules before npm install")
    p.add_argument("--port",       type=int, default=DEFAULT_PORT, metavar="N", help=f"HTTP port (default {DEFAULT_PORT})")
    p.add_argument("--prod",       action="store_true", help="Production mode – no --reload, workers=2")
    p.add_argument("--no-browser", action="store_true", help="Do not open browser automatically")
    p.add_argument("--check",      action="store_true", help="Run service checks only then exit")
    return p.parse_args()


def main():
    args   = parse_args()
    PORT   = args.port

    # ── Banner ────────────────────────────────────────────────────
    print()
    print(_c("1;32", "  ╔══════════════════════════════════════════════════════╗"))
    print(_c("1;32", "  ║") + _c("1;37", "   AgriSahayak — Smart Agriculture Platform v2.3     ") + _c("1;32", "║"))
    print(_c("1;32", "  ╠══════════════════════════════════════════════════════╣"))
    print(_c("1;32", "  ║") + "  Pages   : Home · Crop Advisor · Crop Cycle · Disease  " + _c("1;32", "║"))
    print(_c("1;32", "  ║") + "            Pest · Weather · Market · Chatbot           " + _c("1;32", "║"))
    print(_c("1;32", "  ║") + "            Outbreak Map · Yield Predictor · Fertilizer " + _c("1;32", "║"))
    print(_c("1;32", "  ║") + "            Expenses · Schemes · Satellite · Logistics  " + _c("1;32", "║"))
    print(_c("1;32", "  ║") + "            Analytics · Admin · Soil Passport · Profile " + _c("1;32", "║"))
    print(_c("1;32", "  ╠══════════════════════════════════════════════════════╣"))
    print(_c("1;32", "  ║") + "  AI      : Ollama GPU (local) + Gemini 2.5 Flash       " + _c("1;32", "║"))
    print(_c("1;32", "  ║") + "  UX      : WCAG AA a11y · GPS Mandi · auto-fetch tabs  " + _c("1;32", "║"))
    print(_c("1;32", "  ║") + "  i18n    : 11 langs — sidebar+mobile picker            " + _c("1;32", "║"))
    print(_c("1;32", "  ║") + "  Weather : GPS → real Gemini data · location-aware     " + _c("1;32", "║"))
    print(_c("1;32", "  ║") + "            mock fallback (lat+season) · no hardcoded   " + _c("1;32", "║"))
    print(_c("1;32", "  ║") + "  Sat     : crop-specific NDVI · 5 min cache · round()  " + _c("1;32", "║"))
    print(_c("1;32", "  ║") + "  Market  : haversine GPS dist · state filter · 150 km  " + _c("1;32", "║"))
    print(_c("1;32", "  ║") + "  ML      : Crop Recommender · Yield NN · Pest EfficNet " + _c("1;32", "║"))
    print(_c("1;32", "  ║") + "  DB      : SQLite/PG + Supabase + DuckDB (auto-seed)   " + _c("1;32", "║"))
    print(_c("1;32", "  ║") + "  Crypto  : NeoShield PQC (post-quantum signatures)     " + _c("1;32", "║"))
    print(_c("1;32", "  ╚══════════════════════════════════════════════════════╝"))
    print()

    # ── Paths ─────────────────────────────────────────────────────
    project_root = os.path.dirname(os.path.abspath(__file__))
    backend_dir  = os.path.join(project_root, "backend")
    if not os.path.isdir(backend_dir):
        err(f"Backend directory not found: {backend_dir}")
        sys.exit(1)

    venv_python = (
        os.path.join(project_root, ".venv", "Scripts", "python.exe")
        if sys.platform == "win32"
        else os.path.join(project_root, ".venv", "bin", "python")
    )
    python_exe = venv_python if os.path.exists(venv_python) else sys.executable

    # Ensure .env exists (generate template if missing)
    generate_env_template(project_root)

    runtime_env = prepare_runtime_env(project_root, backend_dir)
    if not runtime_env.get("JWT_SECRET_KEY"):
        err("JWT_SECRET_KEY is required. Set it in .env or backend/.env")
        sys.exit(1)

    lan_ip = get_lan_ip()
    gpu    = check_gpu()
    info("Loaded modules: Satellite Oracle, WhatsApp bot, tokenized DeFi, and quantum fleet optimizer")

    print(f"  Project  : {project_root}")
    print(f"  Python   : {python_exe}")
    print(f"  Local    : http://localhost:{PORT}")
    print(f"  Network  : http://{lan_ip}:{PORT}")
    if gpu:
        print(f"  GPU      : {gpu}")
    if args.prod:
        print(f"  Mode     : production  (no --reload)")
    else:
        print(f"  Mode     : development (--reload on)")
    print()

    # ── Service Checks ────────────────────────────────────────────
    head("=" * 60)
    head("  Service Checks")
    head("=" * 60)
    print()

    # 1. React frontend
    head("  React Frontend (Vite 5 / React 18)")
    build_react_frontend(project_root, force_clean=args.clean)
    print()

    # 1b. npm package check (three · canvas-confetti · html2canvas · jspdf)
    head("  Frontend npm Packages  (three · canvas-confetti · html2canvas · jspdf)")
    check_npm_packages(project_root)
    print()

    # 2. Ollama (local LLM — chatbot + weather summaries)
    head("  Ollama  (local GPU — chatbot + weather summaries)")
    ollama_ok = start_ollama()
    if ollama_ok:
        models = get_ollama_models()
        if models:
            preferred = ["qwen3:30b", "qwen2.5:7b", "llama3.2:latest", "phi3:mini"]
            active    = next((m for m in preferred if m in models), models[0])
            ok(f"Active model: {active}")
            if len(models) > 1:
                others = [m for m in models if m != active][:3]
                info(f"Other models: {', '.join(others)}")
        else:
            warn("No models found. Run:  ollama pull llama3.2")
    print()

    # 3. Gemini 2.5 Flash (weather data + crop advisory + market advisory)
    head("  Gemini 2.5 Flash  (weather · crop advisor · market prices)")
    gemini_key = runtime_env.get("GEMINI_API_KEY", "")
    if gemini_key:
        preview = gemini_key[:6] + "..." + gemini_key[-4:] if len(gemini_key) > 12 else "***"
        ok(f"GEMINI_API_KEY is set  ({preview})")
        info("Powers: weather intelligence, unified forecast, crop advisory, market analysis")
        ok("Markdown stripping active — **bold** / *italic* stripped before UI render")
    else:
        err("GEMINI_API_KEY not set — all Gemini AI features will use rule-based fallbacks")
        info("Get a free key at https://aistudio.google.com/app/apikey")
        info("Add GEMINI_API_KEY=<your-key> to .env and restart")
    print()

    # 4. Market Prices API
    head("  Market Prices  (AGMARKNET / data.gov.in)")
    market_key = runtime_env.get("MARKET_API_KEY", "")
    if market_key:
        ok(f"MARKET_API_KEY is set  ({market_key[:6]}...)")
    else:
        warn("MARKET_API_KEY not set — market page uses cached / mock prices")
        info("Get a free key at https://data.gov.in/ogdp")
    print()

    # 5. Sentinel-2 space intelligence
    head("  Sentinel-2  (NDVI + Carbon + Parametric Insurance)")
    sentinel_client_id = runtime_env.get("SENTINEL_CLIENT_ID", "")
    sentinel_client_secret = runtime_env.get("SENTINEL_CLIENT_SECRET", "")
    if sentinel_client_id and sentinel_client_secret:
        preview = sentinel_client_id[:6] + "..." if len(sentinel_client_id) >= 6 else "***"
        ok(f"SENTINEL credentials are set  ({preview})")
        info("Real satellite analysis enabled for /satellite endpoints")
    else:
        warn("SENTINEL_CLIENT_ID / SENTINEL_CLIENT_SECRET not set")
        info("Satellite endpoints will use deterministic mock NDVI values")
        info("Get free credentials at https://dataspace.copernicus.eu")
    print()

    # 6. Twilio WhatsApp bot
    head("  Twilio WhatsApp Bot  (Zero-G fallback for low-connectivity users)")
    twilio_sid = runtime_env.get("TWILIO_ACCOUNT_SID", "")
    twilio_token = runtime_env.get("TWILIO_AUTH_TOKEN", "")
    twilio_whatsapp_number = runtime_env.get("TWILIO_WHATSAPP_NUMBER", "+14155238886")
    if twilio_sid and twilio_token:
        ok(f"TWILIO credentials are set  (number: {twilio_whatsapp_number})")
        info("Webhook endpoint: POST /api/v1/whatsapp/webhook")
    else:
        warn("TWILIO_ACCOUNT_SID / TWILIO_AUTH_TOKEN not set")
        info("WhatsApp bot endpoints exist but external Twilio integration is inactive")
        info("Set webhook URL in Twilio Sandbox to: /api/v1/whatsapp/webhook")
    print()

    # 7. Supabase
    head("  Supabase  (auth · storage · remote DB — optional)")
    sb_url = runtime_env.get("SUPABASE_URL", "")
    sb_key = runtime_env.get("SUPABASE_KEY", "")
    if sb_url and sb_key:
        project_id = sb_url.replace("https://", "").split(".")[0]
        ok(f"Supabase project: {project_id}")
    else:
        missing = [k for k in ("SUPABASE_URL", "SUPABASE_KEY") if not runtime_env.get(k)]
        warn(f"Missing: {', '.join(missing)} — falling back to local SQLite")
        info("See backend/SUPABASE_SETUP.md to configure remote storage")
    print()

    # 8. DuckDB analytics
    head("  DuckDB  (analytics · outbreak heatmaps · auto-seed)")
    duckdb_path = os.path.join(backend_dir, "analytics.duckdb")
    alt_path    = os.path.join(backend_dir, "analytics", "analytics.duckdb")
    found_path  = next((p for p in (duckdb_path, alt_path) if os.path.exists(p)), None)
    if found_path:
        size_kb = os.path.getsize(found_path) // 1024
        ok(f"analytics.duckdb found  ({size_kb} KB) — outbreak alerts active")
    else:
        info("analytics.duckdb will be created on first API call")
    ok("/disease-heatmap auto-seeds 500 demo records if DuckDB is empty")
    print()

    # 9. ML Models
    head("  ML Models  (crop recommender · yield predictor · pest classifier)")
    check_ml_models(project_root)
    print()

    # 10. PWA / Offline Mode
    head("  PWA / Offline Mode  (Service Worker)")
    sw_path = os.path.join(project_root, "frontend-dist", "sw.js")
    if os.path.exists(sw_path):
        ok("sw.js present — offline caching active")
    else:
        warn("sw.js not found — offline mode disabled")
        if shutil.which("npm"):
            info("Run:  cd frontend-src && npm run build")
    print()

    # 11. Voice Commands
    head("  Voice Commands & TTS  (Web Speech API + Edge-TTS backend)")
    ok("STT input: en hi mr pa gu ta te kn bn")
    ok("TTS primary: native browser voice matched by BCP-47 (when installed)")
    ok("TTS fallback: Edge-TTS backend  (/api/v1/voice/tts) - 9 Microsoft neural voices")
    ok("Languages: hi mr te ta kn bn gu pa ml or en-IN — each has its own neural voice")
    info("No English mispronunciation — backend falls back to Edge-TTS if browser has no native voice")
    print()

    # 12. i18n Language Support
    head("  i18n  (11 Indian languages)")
    ok("Translations: English, Hindi, Marathi, Punjabi, Gujarati, Tamil,")
    ok("              Telugu, Kannada, Bengali, Odia, Malayalam")
    info("Language picker in sidebar (desktop) and mobile header Globe button")
    print()

    # 13. Accessibility (WCAG AA)
    head("  Accessibility  (WCAG AA — PROMPT 7.1 + 7.2)")
    ok("ARIA labels on all icon-only buttons, form fields, live regions")
    ok("Colour contrast: text-3=#9CA3AF, primary=#22C55E, focus-visible ring")
    ok("Text-shadow on gradient hero banners (Home · Disease · Advisor · Fertilizer)")
    print()

    # 14. Recent Fixes
    head("  Recent Fixes  (v2.2 → v2.3)")
    ok("satellite.py    — crop param threaded through analyze_land + DuckDB INSERT")
    ok("duckdb_engine.py — CREATE TABLE moved to init_duckdb() (not per-request)")
    ok("satellite.py    — land_id uses round() to match frontend Math.round()")
    ok("market.py       — haversine GPS distance, state filter, lat/lng Query params")
    ok("satellite.py    — 5-min in-process cache prevents duplicate Sentinel calls")
    ok("SatelliteOracle — Carbon/Insurance tabs auto-fetch on first visit")
    ok("Sidebar.jsx     — Logistics nav uses 'to:' key + bare icon component refs")
    ok("sentinel_service— crop-specific NDVI offsets (15 crops), analysis.crop in UI")
    ok("weather.py      — hardcoded generate_forecast() removed; uses location-aware")
    ok("                  get_mock_forecast/get_mock_current(lat, lon) fallbacks")
    ok("Market.jsx      — MandiNavigator default radius 50 km → 150 km")
    ok("Schemes.jsx     — mojibake fixed (UTF-8 emoji/₹/—/– all restored correctly)")
    ok("frontend-dist   — bundle rebuilt (vite build); stale index-CFyjKC9X.js had")
    ok("                  AnimatePresence used w/o import → crash on app load fixed")
    ok("duckdb_engine.py — migration uses information_schema (not SQLite PRAGMA) to")
    ok("                  check for 'crop' column; drops indexes before ALTER TABLE")
    ok("sentinel_service— mock NDVI now varies per-request (time-seeded RNG + season)")
    ok("satellite.py    — cache key includes crop; carbon/insurance endpoints pass crop")
    print()

    if args.check:
        head("  --check flag: skipping server start.")
        sys.exit(0)

    # ── Pre-flight ────────────────────────────────────────────────
    if is_port_in_use(PORT):
        warn(f"Port {PORT} is already in use — attempting to free it...")
        kill_existing_server(PORT)
        time.sleep(2)

    os.chdir(backend_dir)
    print(f"  Working dir: {os.getcwd()}")
    print()
    head("=" * 60)
    head(f"  Starting FastAPI server on http://localhost:{PORT}")
    head("=" * 60)
    print()

    # Browser open (delayed so server is ready)
    if not args.no_browser:
        def _open():
            time.sleep(4)
            webbrowser.open(f"http://localhost:{PORT}")
            print(f"\n  Browser opened: http://localhost:{PORT}\n")
        threading.Thread(target=_open, daemon=True).start()

    # Pre-warm Ollama model into GPU VRAM (background, best-effort)
    if ollama_ok:
        threading.Thread(target=warmup_ollama_background, daemon=True).start()

    # ── Launch uvicorn ────────────────────────────────────────────
    cmd = [
        python_exe, "-m", "uvicorn",
        "app.main:app",
        "--host", HOST,
        "--port", str(PORT),
        "--log-level", "info",
    ]
    if args.prod:
        cmd += ["--workers", "2"]
    else:
        cmd += ["--reload"]

    try:
        subprocess.run(cmd, check=True, env=runtime_env)
    except KeyboardInterrupt:
        print("\n\n  Server stopped. Goodbye!")
    except subprocess.CalledProcessError as e:
        err(f"Server exited with error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()


